[tool.poetry]
name = "clicker"
version = "0.1.0"
description = ""
authors = ["Felipe Muniz"]

[tool.poetry.dependencies]
python = "^3.9"
urwid = "^2.1.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
